### ISSUE TITLE
Allow blank database password during installation

### ISSUE THREAD

**Issue by jlahijani** [globalis-ms/wp-cubi#47]
When running the installer on the command line, it doesn't allow a blank database password.

**Comment by pierre-dargham** [comment]
Hello @jlahijani ,

Thank you for opening the issue. You're right, we forgot about this case ! 

We will allow empty values for this question. I'll close the issue when it's done.

Bests regards,
Pierre

**Comment by pierre-dargham** [comment]
Done in version 0.6.5 !
 https://github.com/globalis-ms/wp-cubi/releases/tag/0.6.5
